export const moreActionsData = [
  "Name",
  "Status",
  "Email",
  "Call",
  "Phone",
  "Projects",
  "ID",
  "Bad calls",
  "Cost Price",
  "Rating",
  "Created On",
  "Action",
  "Current Company",
  "Geography",
  "Current Designation",
];
export const selectExpertdata = [
  {
    name: "Vinay Verma",
    email: "Vinayverma@gmail.com",
    phone: "+91 1234567890",
    id: "525363",
    cost_price: "2000",
    created_on: "27 July 2022",
    status: "Identified",
    call: "",
    projects: "",
    bad_calls: "",
    rating: "",
    more: true,
    action: {
      is_contact: true,
      is_refuse: false,
      is_reopen: false,
      is_approved: false,
    },
    accept_action: false,
  },
  {
    name: "Debaprasad Sinha",
    email: "Vinayverma@gmail.com",
    phone: "+91 1234567890",
    id: "525363",
    cost_price: "2000",
    created_on: "27 July 2022",
    status: "Contacted",
    call: "",
    projects: "",
    bad_calls: "",
    rating: "",
    more: true,
    action: {
      is_contact: false,
      is_refuse: true,
      is_reopen: false,
      is_approved: false,
    },
    accept_action: true,
  },
  {
    name: "Mr Amol Kulkrani",
    email: "Vinayverma@gmail.com",
    phone: "+91 1234567890",
    id: "525363",
    cost_price: "2000",
    created_on: "27 July 2022",
    status: "Confirmed",
    call: "270",
    projects: "20",
    bad_calls: "5",
    rating: "4.6",
    more: true,
    action: {
      is_contact: false,
      is_refuse: false,
      is_reopen: false,
      is_approved: false,
    },
    accept_action: false,
  },
  {
    name: "Mr Amol Kulkrani",
    email: "Vinayverma@gmail.com",
    phone: "+91 1234567890",
    id: "525363",
    cost_price: "2000",
    created_on: "27 July 2022",
    status: "Pending update",
    call: "270",
    projects: "20",
    bad_calls: "5",
    rating: "4.6",
    more: true,
    action: {
      is_contact: true,
      is_refuse: false,
      is_reopen: false,
      is_approved: false,
    },
    accept_action: false,
  },
  {
    name: "Mr Amol Kulkrani",
    email: "Vinayverma@gmail.com",
    phone: "+91 1234567890",
    id: "525363",
    cost_price: "2000",
    created_on: "27 July 2022",
    status: "Refused",
    call: "270",
    projects: "20",
    bad_calls: "5",
    rating: "4.6",
    more: true,
    action: {
      is_contact: false,
      is_refuse: false,
      is_reopen: true,
      is_approved: false,
    },
    accept_action: false,
  },
  {
    name: "Mr Amol Kulkrani",
    email: "Vinayverma@gmail.com",
    phone: "+91 1234567890",
    id: "525363",
    cost_price: "2000",
    created_on: "27 July 2022",
    status: "Onboarding",
    call: "270",
    projects: "20",
    bad_calls: "5",
    rating: "4.6",
    more: true,
    action: {
      is_contact: false,
      is_refuse: false,
      is_reopen: false,
      is_approved: true,
    },
    accept_action: false,
  },
];
